// models/Goal.js
// Stores long term goals and milestones

const mongoose = require('mongoose');

const MilestoneSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        default: ''
    },
    completed: {
        type: Boolean,
        default: false
    },
    completedAt: {
        type: Date,
        default: null
    },
    dueDate: {
        type: String,
        default: ''
    },
    order: {
        type: Number,
        default: 0
    }
});

const PhaseSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        default: ''
    },
    milestones: [MilestoneSchema],
    completed: {
        type: Boolean,
        default: false
    },
    order: {
        type: Number,
        default: 0
    }
});

const GoalSchema = new mongoose.Schema({
  // Which user owns this goal
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },

  // Goal details
    title: {
        type: String,
        required: [true, 'Goal title is required'],
        trim: true
    },
    description: {
        type: String,
        default: ''
    },

  // Timeline
    duration: {
        type: String,
        default: ''
    },
    startDate: {
        type: String,
        default: ''
    },
    targetDate: {
        type: String,
        default: ''
    },

  // Phases with milestones (AI generated roadmap)
    phases: [PhaseSchema],

  // Progress percentage 0-100
    progress: {
        type: Number,
        default: 0,
        min: 0,
        max: 100
    },

  // Status
    status: {
        type: String,
        enum: ['active', 'completed', 'paused', 'abandoned'],
        default: 'active'
    },

  // Was roadmap generated by AI
    aiGenerated: {
        type: Boolean,
        default: false
    },

  // Category
    category: {
        type: String,
        enum: ['career', 'education', 'health', 'personal', 'financial', 'other'],
        default: 'personal'
    }

}, {
    timestamps: true
});

module.exports = mongoose.model('Goal', GoalSchema);